config/routes.rb
MoonApp::Application.routes.draw do
  resources :categories, :only => [:show]
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :ads, :only => [:create, :destroy]
 
  match '/registration', :to => 'users#new', :as => :registration
  match '/users/:id', :to => 'users#show'
  match '/signin',  :to => 'sessions#new', :as => :signin
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'mypages#contact'
  match '/about',   :to => 'mypages#about'
  match '/',        :to => 'mypages#home'
  
  root :to => 'mypages#home'
  match 'categories/:id', :to => 'categories#show', :as => :cat
  

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  attr_accessible :content
  attr_accessible :email
  
  belongs_to :category
  belongs_to :user
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :content,     :presence => true
  validates :email,       :presence => true,
                          :format   => { :with => email_regex }
  validates :category_id, :presence => true  
  
  
  default_scope :order => 'ads.created_at DESC'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name;
  
  validates(:name, :presence => true)
  
  has_many :ads, :dependent => :destroy
  
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
					:uniqueness => { :case_sensitive => false }
  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
  
  before_save :encrypt_password
  has_many :ads, :dependent => :destroy
   
  def has_password?(submitted_password)
   encrypted_password == encrypt(submitted_password)
  end
   
  def self.authenticate(email, submitted_password)
   user = find_by_email(email)
   return nil  if user.nil?
   return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
	
	def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
   before_filter :authenticate, :only => [:create, :destroy]

  def create
    #@ad  = current_user.ads.build(params[:ad])
	@ad  = Category.find_by_id(2).ads.build(params[:ad])
    if @ad.save
      flash[:success] = "Ad created!"
      redirect_back
	  #redirect_to root_path
    else
      render 'mypages/home'
    end
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  include CategoriesHelper
  # add 06/22/2011
  def current_category=(category_id)
    @current_category = category_id
  end
  # add 06/22/2011
  def current_category
    @current_category
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  #def index
  #  @title = "All Categories"
  #  @categories = Category.all
  #end
  
  def show
    @category = Category.find(params[:id])
	
	@ads = @category.ads.paginate(:page => params[:page], :per_page => 3)
	@title = @category.name
	store_location
	if signed_in?
	  @ad = Ad.new 
	  #post_ad_of @category.id
	  @current_category = @category.id
	end
  end
  
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  def home
    @title = "Home"
	@categories = Category.find(:all)
	
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email],
                           params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user 
	  # comment out the following line
	  # make it back to the selected category page 06/22/2011
	  #redirect_to user
	  redirect_back
    end
	
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Registration"
	@user = User.new
  end
  def show
    @user = User.find(params[:id])
	@title = @user.name
	if signed_in?
      #@feed_items = current_user.feed.paginate(:page => params[:page], :per_page => 3)
	  @ads = current_user.ads.paginate(:page => params[:page], :per_page => 3)
    end
  end
  def create
    @user = User.new(params[:user])
    if @user.save
	  sign_in @user
	  flash[:success] = "Welcome to Tagsmoon's List!"
      redirect_to @user
    else
      @title = "Registration"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = "Ruby on Rails Termproj Moon App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  # add 06/22/2011
  def post_ad_of(category_id)
    current_category = category_id
  end
  # add 06/22/2011
  def current_category=(category_id)
    @current_category = category_id
  end
  # add 06/22/2011
  def current_category
    @current_category
  end
  
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  # add 06/22/2011
  def post_ad_of(category_id)
    current_category = category_id
  end
  # add 06/22/2011
  def current_category=(category_id)
    @current_category = category_id
  end
  # add 06/22/2011
  def current_category
    @current_category
  end
  
  def current_user=(user)
    @current_user = user
  end
 
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def authenticate
    deny_access unless signed_in?
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  
  def redirect_back
    redirect_to(session[:return_to])
    clear_return_to
  end
  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
	
	def store_location
      session[:return_to] = request.fullpath
    end
	def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ads/_ad.html.erb
<tr>
  <td class="ad">    
    <span class="timestamp">
	  <strong>Post id:</strong> <%= 10000000+ad.id %>&nbsp;&nbsp;&nbsp;
      <strong>Posted on:</strong> <%= ad.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
    </span>
	<span class="email"><strong>Sailer's email:</strong> <%= ad.email %></span>
	<span class="content"><%= ad.content %></span>	
  </td>
</tr>

app/views/categories/index.html.sav.erb
<h2>All categories</h1>
<% @categories.each do |category| %>
<%= category.name %><br/>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name.capitalize %></h1>
<% if signed_in? %>  
  <%= form_for @ad do |f| %> 
    <div class="field">
      <%= f.label :"Sailer's email " %><br/>
      <%= f.text_field :email %>
    </div>
    <div class="field">
	  <%= f.label :Description %><br/>
      <%= f.text_area :content %>
    </div>
    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
  <% end %>
<% end %>

<table class="main">
  <tr>
    <% if !signed_in? %>
      <td><%= link_to "Please sign in to post ads", signin_path %></td>
	<% else %>
	  <td><%= "Please post your ad!" %></td>
	  
	<% end %>
  </tr>
</table>
<table class="profile">
  <tr>
    <td class="main">
      <% unless @category.ads.empty? %>
        <table class="ads" summary="Category ads">
          <%= render @ads %>
        </table>
        <%= will_paginate @ads %>
      <% end %>
    </td>
  </tr>
</table>

app/views/categories/show.html.sav.erb
<h1><%= @category.name.capitalize %></h1>

<% if signed_in? %>
  <%= form_for @ad do |f| %>
    <div class="field">
      <%= f.label :"Sailer's email " %><br/>
      <%= f.text_field :email %>
    </div>
    <div class="field">
	  <%= f.label :Description %><br/>
      <%= f.text_area :content %>
    </div>
    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
  <% end %>
<% end %>

<table class="main">
  <tr>
    <% if !signed_in? %>
      <td><%= link_to "Please sign in to post ads", signin_path %></td>
	<% else %>
	  <td><%= "Please post your ad!" %></td>
	<% end %>
  </tr>
</table>
<table class="profile">
  <tr>
    <td class="main">
      <% unless @category.ads.empty? %>
        <table class="ads" summary="Category ads">
          <%= render @ads %>
        </table>
        <%= will_paginate @ads %>
      <% end %>
    </td>
  </tr>
</table>

app/views/layouts/_footer.html.erb
<footer>
  <h4><%= link_to "Contact us", contact_path %>&nbsp;|&nbsp;
      <%= link_to "About", about_path %>&nbsp;|&nbsp;
	  &copy; 2011 All right reserved.</h4>
</footer>

app/views/layouts/_header.html.erb
<head>
  <% logo = image_tag("logo.jpg", :alt => "Tagsmoon List") %>
  <%= link_to logo, root_path %>
</head>

app/views/layouts/_navigation.html.erb
<nav class="round">
  <h2>Welcome</h2><br/>
  <ul>
    <li><%= link_to "Home", root_path %></li><br/><br/>
    <li><%= link_to "New user registration", registration_path %></li><br/>
	<% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li><br/>
    <% else %>
      <li><%= link_to "Sign in to post ads", signin_path %></li><br/>
	<% end %>
  </ul>
</nav>

app/views/layouts/_news.html.erb
<news class="round">
  <h2>What's new?</h2><br/>
  <%= render 'shared/news_article' %>
</news>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->   
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
</head> 
<body>
  <div class="container">
    <%= render 'layouts/header' %>
	  <div class="content">
	    <%= render 'layouts/navigation' %>	
	    <section>
		  <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
          <% end %>
	      <%= yield %>
	    </section>
	    <%= render 'layouts/news' %>
	    </div>
	  <%= render 'layouts/footer' %>
  </div> 
</body>
</html>

app/views/mypages/about.html.erb
<h1>About Us</h1>
<p>
  <a href="http://www.sidewayslogic.com">Tagsmoon's List</a>
  provides a platform for online advertisement.
</p>
 

app/views/mypages/contact.html.erb
<h1>Contact</h1>
<p>
  You may contact us at 
  <a href="http://www.sidewayslogic.com">Tagsmoon's List</a>. Please note that  
  turnaround time is normally between 24 to 48 hours (except on holidays).
</p>

app/views/mypages/home.html.erb
<h1>Tagsmoon's List</h1>
<p>
    <a href="http://sidewayslogic.com/">Tagsmoon's List</a>
    provides a platform for users to advertise and sail merchandises
	online. 
	<br/>
	<%= render 'shared/category' %>
	
</p>

app/views/shared/_ad_form.html.erb
<%= form_for @category.ads do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_category.html.erb
<h2>All categories</h2>

<% categories = Category.find :all, :limit => 6 %>
<p>
  <% categories.each do |item| %>
  <% @category = item %>
  <%= link_to item.name, cat_url(item.id) %><br/>
  <% end %>
</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_news_article.html.erb
<p>
  <% news = News.find :all, :limit=>2, :order=>'date desc' %>
  <% news.each do |item| %>
    <b><%= item.title %></b><br/>
    <%= item.date.strftime("%Y-%m-%d %H:%M:%S") %><br/><br/>
    <%= item.article %><br/><br/>
  <% end %>
</p>

app/views/users/new.html.erb
<h1><%= @title %></h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
	  <% unless @user.ads.empty? %>
        <table class="ads" summary="User ads">
		  <h1 class="ad">Ads</h1>
          <%= render @ads %>
        </table>
        <%= will_paginate @ads %>
      <% end %>
    </td>
  </tr>
</table>